title: Ben M. Andrew
author: Ben Andrew
email: benmandrew@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Programming blog and portfolio.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://benmandrew.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: benmandrew
github_username:  benmandrew

timezone: Europe/London

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-analytics

s3_path: "https://benmandrew.s3.eu-west-2.amazonaws.com"

permalink: /:categories/:title

jekyll_analytics:
  GoogleAnalytics:
    id: G-XEX6K5B1LZ
    anonymizeIp: false

exclude:
  - Gemfile
  - Gemfile.lock
  - bin/
  - README.md
