on: [push, pull_request]

name: Spellcheck

jobs:
  check:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install spellchecker
        uses: tbroadley/spellchecker-cli-action@v1

      - name: A
        run: spellchecker -q --no-suggestions --language en-GB _posts/* --reports all.json --dictionaries bin/spellcheck.dictionary

      - name: Run spellchecker against expected
        run: ./bin/spellcheck
