on: [push, pull_request]

name: Spellcheck

jobs:
  check:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Set up Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Install spellchecker
        run: npm install --global spellchecker-cli

      - name: Check
        continue-on-error: true
        run: spellchecker -q --no-suggestions --language en-GB _posts/* --reports all.json --dictionaries bin/spellcheck.dictionary

      - name: Diff against expected
        run: ./bin/spellcheck
