on: [push, pull_request]

name: Build

jobs:
  check:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install spellchecker
        uses: tbroadley/spellchecker-cli-action@v1

      - name: Run spellchecker against expected
        run: ./bin/spellcheck
